config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get '/dashboard', to: 'pages#dashboard', as: :dashboard
  resources :toilets, only: [:index, :new, :show, :create, :destroy] do
    resources :bookings, only: [:new, :create]
  end
  resources :bookings, only: [:destroy] do
    resources :reviews, only: [:new, :create]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  has_one :review, dependent: :destroy
  belongs_to :toilet
  belongs_to :user

  validates :date_start, presence: true
  validates :date_end, presence: true
  validates :message, presence: true
  validates :message, length: { minimum: 6 }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :booking

  validates :rating, presence: true
  validates :comment, presence: true
  validates :comment, length: { minimum: 10 }
end

app/models/toilet.rb
class Toilet < ApplicationRecord
  belongs_to :user
  has_many :bookings
  has_many :users, through: :bookings
  has_many_attached :photos

  geocoded_by :location
  after_validation :geocode, if: :will_save_change_to_location?
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :toilets
  has_many :bookings
  has_many :toilets, through: :bookings
  has_one_attached :photo
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:photo])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def new
    @toilet = Toilet.find(params[:toilet_id])
    @booking = Booking.new
  end

  def create
    @toilet = Toilet.find(params[:toilet_id])
    @booking = Booking.new(booking_params)
    @booking.toilet = @toilet
    @booking.user_id = current_user.id

    if @booking.save
      redirect_to dashboard_path(current_user)
    else
      render :new
    end
  end

  def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy

    redirect_to dashboard_path(current_user)
  end

  private

  def booking_params
    params.require(:booking).permit(:message, :date_start, :date_end)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  def home
  end

  def dashboard
    @user = current_user
    @bookings = @user.bookings

    @toilets = Toilet.where(user: @user)
    @bookings_of_your_toilets = []
    @toilets.each do |toilet|
      toilet.bookings.each do |booking|
        @bookings_of_your_toilets << booking
      end
    end
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @booking = Booking.find(params[:booking_id])
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @booking = Booking.find(params[:booking_id])
    @toilet = @booking.toilet
    @review.booking = @booking
    if @review.save
      redirect_to toilet_path(@toilet)
    else
      render :new
    end
  end

  private

  def review_params
    params.require(:review).permit(:rating, :comment)
  end
end

app/controllers/toilets_controller.rb
class ToiletsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home,:index]

  def index
    if params[:query].present?
      @toilets = Toilet.where("location ILIKE ?", "%#{params[:query]}%")
    else
      @toilets = Toilet.all
    end

    @markers = @toilets.geocoded.map do |toilet|
      {
        lat: toilet.latitude,
        lng: toilet.longitude,
        info_window: render_to_string(partial: "info_window", locals: { toilet: toilet }),
        image_url: helpers.asset_url('poop.gif')
      }
    end
  end




  def new
    @toilet = Toilet.new
  end

  def show
    @toilet = Toilet.find(params[:id])
    @bookings = @toilet.bookings
    @reviews = []
    @bookings.each do |booking|
      if booking.review
        @reviews << booking.review
      end
    end
  end

  def create
    @toilet = Toilet.new(toilet_params)
    @toilet.user_id = current_user.id
    if @toilet.save
      redirect_to toilet_path(@toilet)
    else
      render :new
    end
  end

  def destroy
    @toilet = Toilet.find(params[:id])
    @toilet.destroy

    redirect_to dashboard_path
  end

  private

  def toilet_params
    params.require(:toilet).permit(:name, :description, :location, :price, photos: [])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/new.html.erb
<%= simple_form_for [ @toilet, @booking ] do |f| %>
  <%= f.input :message %>
  <%= f.input :date_start %>
  <%= f.input :date_end%>
  <%= f.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ToiletsAirbnb</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application' %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.10/css/all.css">

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>

    <div class="content-push"><%= yield %></div>
    <%= render 'shared/flashes' %>
  </body>
</html>

app/views/pages/dashboard.html.erb
<div class = page-container>
  <h2 class="text-center">Welcome <%= @user.email %>!</h2>
  <p class="button p-4"><%= link_to "Share my toilet", new_toilet_path %></p>
  <h3 class="p-4">Your toilets: </h3>
  <div class="cards-your-toilet">
    <% @toilets.each do |toilet| %>
    <div class="card-your-toilet">
      <div class="image">
        <% if toilet.photos.attached? %>
          <% toilet.photos.each do |photo| %>
            <div class="toilet-img" style="background-image: url('<%= cl_image_path photo.key %>')"></div>
          <% end %>
        <% end %>
      </div>
      <div class="content">
        <h4><%= link_to toilet.name, toilet_path(toilet) %></h4>
        <p><%= toilet.description %></p>
      </div>
      <div class="button delete">
        <p><%= link_to "Delete", toilet_path(toilet), method: :delete, data: {confirm: "Are you sure?"} %></p>
      </div>
    </div>
    <% end %>
  </div>


  <h3 class="p-4">Bookings of your toilets:</h3>
  <div class="cards-your-toilet">
    <% @bookings_of_your_toilets.each do |booking| %>
    <div class="card-your-toilet">
      <div class="image">
        <% if booking.toilet.photos.attached? %>
          <% booking.toilet.photos.each do |photo| %>
            <div class="toilet-img" style="background-image: url('<%= cl_image_path photo.key %>')"></div>
          <% end %>
        <% end %>
      </div>
      <div class="content">
        <h4><%= link_to booking.toilet.name, toilet_path(booking.toilet) %></h4>
        <p>from: <em><%= booking.date_start %></em></p>
        <p>until: <em><%= booking.date_end %></em></p>
        <p>"<%= booking.message %>" </p>
      </div>
      <div class="button delete">
        <%= link_to "decline booking", booking_path(booking), method: :delete, data: { confirm: "Are you sure?"} %>
      </div>
    </div>
    <% end %>
  </div>

  <h3 class="p-4">Your bookings:</h3>
  <div class="cards-your-toilet">
    <% @bookings.each_with_index do |booking, index| %>
    <div class="card-your-toilet">
      <div class="image">
        <% if booking.toilet.photos.attached? %>
          <% booking.toilet.photos.each do |photo| %>
            <div class="toilet-img" style="background-image: url('<%= cl_image_path photo.key %>')"></div>
          <% end %>
        <% end %>
      </div>
      <div class="content">
        <h4><%= link_to booking.toilet.name, toilet_path(booking.toilet)  %></h4>
        <p>from: <em><%= booking.date_start %></em></p>
        <p>until: <em><%= booking.date_end %></em></p>
        <p>"<%= booking.message %>"</p>
      </div>
      <div class="button delete">
        <%= link_to "cancel booking", booking_path(booking), method: :delete, data: { confirm: "Are you sure?"} %>
        <%= link_to 'Leave a review', new_booking_review_path(booking) %>
      </div>
    </div>
    <% end %>
  </div>
</div>
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    This website is made with <i class="fas fa-poo"></i> at TopLets
  </div>
</div>

app/views/pages/home.html.erb
<div class="banner button">
  <h1>Easily find the best toilet in town!</h1>
  <%= link_to "Find a toilet", toilets_path %>
</div>
<br>
<br>
<div class="share-toilet-container button">
    <h2>Having the perfect toilet ? Contribute to our community !</h2>
    <%= link_to "share my toilet", new_toilet_path %>
</div>

<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    This website is made with <i class="fas fa-poo"></i> at TopLets
  </div>
</div>

app/views/reviews/new.html.erb
<%= simple_form_for [ @booking, @review ] do |f| %>
  <%= f.input :rating %>
  <%= f.input :comment %>
  <%= f.submit "Submit review", class: "btn btn-primary" %>
<% end %>

app/views/reviews/review.html.erb
<%= simple_form_for [ @booking, @review ] do |f| %>
  <%= f.input :rating %>
  <%= f.input :comment %>
  <%= f.submit %>
<% end %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-sm navbar-light navbar-lewagon fixed-top">
    <div class="logo-link">
      <%= link_to root_path do %>
        <i class="fas fa-toilet-paper"></i>
        <span>Toplets</span>
      <% end %>
    </div>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <% if user_signed_in? %>
        <div class="nav-item dropdown">
        <% if current_user.photo.attached? %>
          <%= cl_image_tag current_user.photo.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% else %>
          <%= image_tag ("cat-profile.jpg") , class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
        <% end %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Find a toilet", "/toilets", class: "dropdown-item" %>
            <%= link_to "Share a toilet", "/toilets/new", class: "dropdown-item" %>
            <%= link_to "Your profile", dashboard_path(current_user), class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </div>
      <% else %>
        <div class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </div>
      <% end %>
    </ul>
  </div>
</nav>

app/views/toilets/_info_window.html.erb
<h2><%= toilet.name %></h2>
<p><%= toilet.location %></p>

app/views/toilets/index.html.erb
<div class="index-page">
  <div class="search-results">
    <div class="searchblock">
      <div class="searchbar">
        <%= form_tag toilets_path, method: :get do %>
          <%= text_field_tag :query,
            params[:query],
            class: "form-control",
            placeholder: "Find a toilet"
          %>
        <% end %>
      </div>
      <div class="fixbutton">
        <div class="submit-button">
          <%= button_tag "Submit", type: "submit", class: "magnifier" do %>
            <div class="loupe">
              <i class="fas fa-search"></i>
            </div>
          <% end %>
        </div>
      </div>
    </div>
    <br>
    <br>
    <h2>Toilets in the area</h2>
    <div class="toilet-index-container text-decoration">
      <div class="cards-index">
        <% @toilets.each do |toilet| %>
          <hr class="line">
          <div class="card-index">
            <div class="picture">
              <% if toilet.photos.attached? %>
                <% toilet.photos.each do |photo| %>
                  <div class="toilet-img" id="toilet-index" style="background-image: url('<%= cl_image_path photo.key %>')"></div>
                <% end %>
              <% end %>
            </div>
            <div class="card-info">
              <div class="titleandlocation">
                <h3 class="card-title"><%= link_to toilet.name, toilet_path(toilet) %></h3>
                <h4 class="card-location"><%= toilet.location %></h4>
              </div>
              <%# <hr class="inside-line"> %>
              <p class="text">"<%= toilet.description %>"</p>
            </div>
          </div>
        <% end %>
      </div>
      <br>
      <br>
      <br>
      <br>
    </div>
  </div>
  <div id="map"
      style="width: 40%; height: 800px"
      data-markers="<%= @markers.to_json %>"
      data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
  </div>
</div>
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    This website is made with <i class="fas fa-poo"></i> at TopLets
  </div>
</div>

app/views/toilets/new.html.erb
<%= simple_form_for(@toilet) do |f| %>
  <%= f.input :name %>
  <%= f.input :photos, as: :file, input_html: { multiple: true} %>
  <%= f.input :description %>
  <%= f.input :location %>
  <%= f.input :price %>
  <%= f.submit %>
<% end %>

app/views/toilets/show.html.erb
<div class= "toilet-container">
  <h2><%= @toilet.name %></h2>
  <ul class ='toilet'>
    <% if @toilet.photos.attached? %>
      <% @toilet.photos.each do |photo| %>
        <li><div class='toilet-img' style="background-image: url('<%= cl_image_path photo.key %>')"></div></li>
      <% end %>
    <% end %>
    <div class="toilet-description">
      <li><i class="fas fa-arrow-right"></i><%= @toilet.description %></li>
      <li><i class="fas fa-map-marker"></i><%= @toilet.location %></li>
      <li><i class="fas fa-euro-sign"></i><%= @toilet.price %> euros</li>
      <li><i class="fas fa-paper-plane"></i><%= @toilet.user.email %></li>
    </div>
      <br>
    <li class='btn-grey'><%= link_to "add a booking", new_toilet_booking_path(@toilet) %></li >
  </ul>
  <ul>
    <% if !@reviews.empty? %>
      <h3>Reviews</h3>
      <% @bookings.each do |booking| %>
        <% if booking.review %>
          <li><%= booking.review.comment %> Rating:<%= booking.review.rating %>/10</li>
        <% end %>
      <% end %>
    <% end %>
  </ul>
</div>